[package]
name = "server"
version = "0.1.0"
authors = ["luca <b.luca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
bincode = "1.3.3"
sha2 = "0.9.3"